import JobCard from '@/components/JobCard';
import { JobDetails } from '@/types';
import { useState } from 'react';

const jobsExample: JobDetails[] = [
  {
    employer_name: 'employer_name1',
    employer_website: 'employer_website',
    job_publisher: 'job_publisher',
    job_title: 'job1',
    job_apply_link: 'job_apply_link',
    job_description: 'job_description',
    job_is_remote: false,
    job_posted_at_datetime_utc: 'May 2024',
    job_city: 'job_city',
    job_country: 'job_country',
    job_job_title: 'job_job_title',
    job_min_salary: 50,
    job_max_salary: 100,
    employer_logo: '',
    employer_company_type: '',
    job_id: '',
    job_employment_type: '',
    job_apply_is_direct: false,
    job_apply_quality_score: 0,
    job_posted_at_timestamp: 0,
    job_state: '',
    job_benefits: null,
    job_google_link: '',
    job_required_experience: {
      no_experience_required: true,
      required_experience_in_months: 10,
      experience_mentioned: true,
      experience_preferred: true,
    },
  },
  {
    employer_name: 'employer_name2',
    employer_website: 'employer_website',
    job_publisher: 'job_publisher',
    job_title: 'job2',
    job_apply_link: 'job_apply_link',
    job_description: 'job_description',
    job_is_remote: false,
    job_posted_at_datetime_utc: 'May 2024',
    job_city: 'job_city',
    job_country: 'job_country',
    job_job_title: 'job_job_title',
    job_min_salary: 50,
    job_max_salary: 100,
    employer_logo: '',
    employer_company_type: '',
    job_id: '',
    job_employment_type: '',
    job_apply_is_direct: false,
    job_apply_quality_score: 0,
    job_posted_at_timestamp: 0,
    job_state: '',
    job_benefits: null,
    job_google_link: '',
    job_required_experience: {
      no_experience_required: true,
      required_experience_in_months: 10,
      experience_mentioned: true,
      experience_preferred: true,
    },
  },
  {
    employer_name: 'employer_name3',
    employer_website: 'employer_website',
    job_publisher: 'job_publisher',
    job_title: 'job3',
    job_apply_link: 'job_apply_link',
    job_description: 'job_description',
    job_is_remote: false,
    job_posted_at_datetime_utc: 'May 2024',
    job_city: 'job_city',
    job_country: 'job_country',
    job_job_title: 'job_job_title',
    job_min_salary: 50,
    job_max_salary: 100,
    employer_logo: '',
    employer_company_type: '',
    job_id: '',
    job_employment_type: '',
    job_apply_is_direct: false,
    job_apply_quality_score: 0,
    job_posted_at_timestamp: 0,
    job_state: '',
    job_benefits: null,
    job_google_link: '',
    job_required_experience: {
      no_experience_required: true,
      required_experience_in_months: 10,
      experience_mentioned: true,
      experience_preferred: true,
    },
  },
  {
    employer_name: 'employer_name4',
    employer_website: 'employer_website',
    job_publisher: 'job_publisher',
    job_title: 'job4',
    job_apply_link: 'job_apply_link',
    job_description: 'job_description',
    job_is_remote: false,
    job_posted_at_datetime_utc: 'May 2024',
    job_city: 'job_city',
    job_country: 'job_country',
    job_job_title: 'job_job_title',
    job_min_salary: 50,
    job_max_salary: 100,
    employer_logo: '',
    employer_company_type: '',
    job_id: '',
    job_employment_type: '',
    job_apply_is_direct: false,
    job_apply_quality_score: 0,
    job_posted_at_timestamp: 0,
    job_state: '',
    job_benefits: null,
    job_google_link: '',
    job_required_experience: {
      no_experience_required: true,
      required_experience_in_months: 10,
      experience_mentioned: true,
      experience_preferred: true,
    },
  },
];

export const Jobs = (): JSX.Element => {
  // const [jobs, setJobs] = useState<JobDetails[]>(jobsExample);

  const jobCards = jobsExample.map((job) => (
    <JobCard key={job.job_id} jobDetails={job} />
  ));

  return <section>{jobCards}</section>;
};

export default Jobs;
